[package]
edition = "2021"
name = "tracing-attributes-http"
publish = false
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-traits", "full"] }

[dev-dependencies]
trybuild = "1"